### PR TITLE
Updating to latest locust, python and alpine

### PR DESCRIPTION
**Pull request by emilorol**

### CODE REVIEW

**Comment by karol-brejna-i** [comment]
At the  first glance, looks great! ;-)

I'll try to run the tests to see if it actually works. Or maybe you'll have some time to update the tests (or https://github.com/karol-brejna-i/docker-locust/tree/master/examples)...

Thank you for the contribution. I'll check it this weekend.

**Comment by emilorol** [comment]
I was able to build the image, but I had to add missing dependency `libffi-dev` otherwise python will not finish doing its thing. After building it I was able to run it as `standalone`. Here are some pictures:

locus
version

**Comment by emilorol** [comment]
Any luck testing it?

**Comment by karol-brejna-i** [comment]
Sorry for the delay. An unexpected break from work. Will revisit the PR in a few days.

**Comment by emilorol** [comment]
No worries, all good.

**Comment by karol-brejna-i** [comment]
My tests are passing. Must remember about updating /example to include the latest locust version...
Thanks for the contribution!

**Pull request merged**
