### PR TITLE
Support for locust 1.2.3

### PR DESCRIPTION
**Pull request by gustavobgama**
Add support for locust `1.2.3`.

### CODE REVIEW

**Comment by karol-brejna-i** [comment]
@gustavobgama Let's discuss the example placement.
Initially, there was only one example (for versions 0.x). Then 1.x came with breaking changes so now there is 0.13.5 folder and 1.0.2 folder. Plus the one you suggested (1.2.3). 
I was thinking about having one example folder for each line, for example 0.x, 1.x, etc.
What do you think?

**Comment by karol-brejna-i** [comment]
@gustavobgama, do you mind updating the README also (slave --> worker). See: https://github.com/karol-brejna-i/docker-locust/issues/17

**Comment by gustavobgama** [comment]
Hi @karol-brejna-i, I think it is a good idea to maintain only one example for each locust line. I'm going to remove the example I added and I can also update the README.

**Comment by karol-brejna-i** [comment]
I'll merge this PR in a few days (away from "real" computer, not able to test).

**Comment by karol-brejna-i** [comment]
Small problem with running the examples:
```Starting master      ... done
Starting 103_slave_1 ... done
Attaching to 103_slave_1, master
slave_1   | standard_init_linux.go:211: exec user process caused "no such file or directory"
master    | standard_init_linux.go:211: exec user process caused "no such file or directory"
103_slave_1 exited with code 1```

Investigating.

**Pull request merged**
