### PR TITLE
Updating examples to include the latest locust version

### PR DESCRIPTION
**Pull request by emilorol**

### CODE REVIEW

**Comment by emilorol** [comment]
Can you add the new version to DockerHub?

**Comment by karol-brejna-i** [comment]
This exapmle shows that the change (update of Locust, Python and OS version) deosn't work:
```
Attaching to examples_slave_1, master
slave_1   | usage: locust [-h] [-H HOST] [--web-host WEB_HOST] [-P PORT] [-f LOCUSTFILE]
slave_1   |               [--csv CSVFILEBASE] [--csv-full-history] [--master] [--slave]
slave_1   |               [--master-host MASTER_HOST] [--master-port MASTER_PORT]
slave_1   |               [--master-bind-host MASTER_BIND_HOST]
slave_1   |               [--master-bind-port MASTER_BIND_PORT]
slave_1   |               [--heartbeat-liveness HEARTBEAT_LIVENESS]
slave_1   |               [--heartbeat-interval HEARTBEAT_INTERVAL]
slave_1   |               [--expect-slaves EXPECT_SLAVES] [--no-web] [-c NUM_CLIENTS]
slave_1   |               [-r HATCH_RATE] [-t RUN_TIME] [--skip-log-setup] [--step-load]
slave_1   |               [--step-clients STEP_CLIENTS] [--step-time STEP_TIME]
slave_1   |               [--loglevel LOGLEVEL] [--logfile LOGFILE] [--print-stats]
slave_1   |               [--only-summary] [--no-reset-stats] [--reset-stats] [-l]
slave_1   |               [--show-task-ratio] [--show-task-ratio-json] [-V]
slave_1   |               [--exit-code-on-error EXIT_CODE_ON_ERROR] [-s STOP_TIMEOUT]
slave_1   |               [LocustClass [LocustClass ...]]
slave_1   | locust: error: Unexpected value for LOCUST_MASTER: 'master'. Expecting 'true', 'false', 'yes', 'no', '1' or '0'
```

I am reverting last merge, until we fix the issue. Can you take a look at this?

**Comment by emilorol** [comment]
Let me check

**Comment by emilorol** [comment]
Very odd. I set the following [ENV ](https://github.com/karol-brejna-i/docker-locust/blob/ac893b7da196fe71c6f971acf716f5a839d1d775/examples/docker-compose-distributed.yml#L25)variable to `0` and start to work, but it can not see the slave.

See my output:

```
➜  docker-locust git:(master) ✗ docker-compose -f examples/docker-compose-distributed.yml up
Starting master ... 
Recreating examples_slave_1 ... done
Attaching to master, examples_slave_1
master    | [2020-01-23 17:46:11,599] master/INFO/locust.main: Starting web monitor at http://*:8089
master    | [2020-01-23 17:46:11,599] master/INFO/locust.main: Starting Locust 0.13.5
slave_1   | [2020-01-23 17:46:11,758] 77954fae50a3/INFO/locust.main: Starting Locust 0.13.5
```

I am going to keep digging.

**Comment by emilorol** [comment]
The current changes enable the latest version to work in a distributed mode. Please test it when you get a chance.

List of changes:

* Updating `ENV` variable name from `LOCUST_MASTER` to `LOCUST_MASTER_HOST`
* Update the example `locustfile.py` to handle latest version deprecation 
* **Standalone** and **Headless** ansible scripts updated too

**Comment by emilorol** [comment]
Any luck testing?

**Comment by karol-brejna-i** [comment]
Yeah, Just finished. I got confused -- in distributed mode no requests were made. I shrank min/max delay and it started to show positive results. Thanks for the

**Pull request merged**
